
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 50
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - aks-nodepool1-65804570-vmss000000
      containers:
        - image: "nginx"
          imagePullPolicy: IfNotPresent
          name: myapp
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 64Mi