apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-node-scheduler-policy
  namespace: kube-system
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "predicates" : [
      {"name" : "PodFitsHostPorts"},
      {"name" : "PodFitsHost"},
      {"name" : "PodFitsResources"},
      {"name" : "PodMatchNodeSelector"},
      {"name" : "NoVolumeZoneConflict"},
      {"name" : "NoDiskConflict"},
      {"name" : "MaxCSIVolumeCount"},
      {"name" : "CheckNodeMemoryPressure"},
      {"name" : "CheckNodePIDPressure"},
      {"name" : "CheckNodeDiskPressure"},
      {"name" : "CheckNodeCondition"},
      {"name" : "PodToleratesNodeTaints"},
      {"name" : "CheckVolumeBinding"}
    ],
    "priorities" : [
      {"name" : "InterPodAffinityPriority", "weight" : "1"},
      {"name" : "LeastRequestedPriority", "weight" : "1"},
      {"name" : "MostRequestedPriority", "weight" : 50},
      {"name" : "RequestedToCapacityRatioPriority", "weight" : "1"},
      {"name" : "BalancedResourceAllocation", "weight" : "1"},
      {"name" : "NodePreferAvoidPodsPriority", "weight" : 1},
      {"name" : "NodeAffinityPriority", "weight" : 50},
      {"name" : "TaintTolerationPriority", "weight" : "1"},
      {"name" : "ImageLocalityPriority", "weight" : "1"},
      {"name" : "ServiceSpreadingPriority", "weight" : "1"},
      {"name" : "CalculateAntiAffinityPriorityMap", "weight" : "1"},
      {"name" : "EqualPriorityMap", "weight" : "1"}
    ],
    "hardPodAffinitySymmetricWeight" : 10
  }
---
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
algorithmSource:
  policy:
    configMap:
      namespace: kube-system
      name: virtual-node-scheduler-policy